### ISSUE TITLE
Getting browsername="Safari" on Chrome browser

### ISSUE THREAD

**Issue by ShahidNaumanTEO** [gauravkk22/browser-detector#1]
The component is returning **`Safari`** as the browser name instead of **`Chrome`** on my machine. I am using **Chrome 49.0.2623.112**  on **Mac OS X 10.7.5**.

The **navigator.userAgent** is returning:
**`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36`**

**Comment by gauravonly** [comment]
Hi Shahid. 
Thanks a lot for the query. While i was developing this component the version of chrome was around 55+ and that is the reason why older version of chrome may be causing problem cause it was untested on that. The easiest way to handle this is by updating your browser to the latest one( 60+) and if it is difficult for you to update then i will find another solution and revert back to you soon.
Thanks

**Comment by ShahidNaumanTEO** [comment]
I found the solution to that issue. It need you to change the `line 37` of **`browser-detector.js`** for detcting older versions of Chrome browsers on Macintosh Operating Systems. 

```
// Safari 3.0+ "[object HTMLElementConstructor]"
var isSafari = /constructor/i.test(window.HTMLElementConstructor) || (function (p) {
	return p.toString() === "[object SafariRemoteNotification]";
})(!window['safari'] || (typeof safari !== 'undefined' && safari.pushNotification));
```

**Comment by gauravonly** [comment]
Hi Shahid. Thanks for your time and help to improve this component. Changes are done  and published on npm. Do check it once again. https://www.npmjs.com/package/polymer-browser-detector
